<?xml version="1.0" encoding="utf-8"?>
<AttributeImageConfig xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <attributelogicalname>f26c_image</attributelogicalname>
  <parententitylogicalname>f26c_disruptionimages</parententitylogicalname>
  <canstorefullimage>1</canstorefullimage>
</AttributeImageConfig>