name: Terraform Deploy

on:
  workflow_dispatch:
    inputs:
      action: 
        description: 'Action to perform (plan or apply)'
        required: true
        default: 'plan'
        type: choice
        options:
          - plan
          - apply
        

permissions:
  contents: read

jobs:
  terraform:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          authentication-method: 'service-principal'
          subscriptionId: "${{ secrets.SUBSCRIPTION_ID }}"
          tenantId: "${{ secrets.TENANT_ID }}"
          clientId: "${{ secrets.CLIENT_ID }}"
          objectId: "${{ secrets.OBJECT_ID }}"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve tfplan